Repository dalbitresb12/zion-escape, pull requests merged in 2020-11, with the labels that each got.

#1 Fixed typos in issues and PR templates
  .github/ISSUE_TEMPLATE/BUG_REPORT_SPA.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST_SPA.md
Labels: enhancement

#4 Created Sprite and Entity class
  ZionEscape/Entity.h
  ZionEscape/Sprite.h
  ZionEscape/ZionEscape.vcxproj
  ZionEscape/ZionEscape.vcxproj.filters
Labels: enhancement

#2 Created BitmapManager
  ZionEscape/BitmapManager.h
  ZionEscape/ZionEscape.vcxproj
  ZionEscape/ZionEscape.vcxproj.filters
Labels: enhancement

#8 Refactored BitmapManager to singleton class
  ZionEscape/BitmapManager.h
Labels: enhancement

#5 Añadida la clase Player
  ZionEscape/Entity.h
  ZionEscape/MainActivity.h
  ZionEscape/Player.cpp
  ZionEscape/Player.h
  ZionEscape/Sprite.h
  ZionEscape/ZionEscape.vcxproj
  ZionEscape/ZionEscape.vcxproj.filters
Labels: enhancement

#6 Pathfinder utilizando el algoritmo A*
  ZionEscape/Entity.h
  ZionEscape/Grid.h
  ZionEscape/MainActivity.h
  ZionEscape/MainActivity.resx
  ZionEscape/MathUtils.h
  ZionEscape/Node.h
  ZionEscape/Pathfinder.h
  ZionEscape/Player.cpp
  ZionEscape/Player.h
  ZionEscape/Sprite.h
  ZionEscape/ZionEscape.vcxproj
  ZionEscape/ZionEscape.vcxproj.filters
Labels: enhancement

#7 Generación de Mapa
  ZionEscape/Game.h
  ZionEscape/MainActivity.h
  ZionEscape/Map.h
  ZionEscape/Scene.h
  ZionEscape/SceneSpawner.h
  ZionEscape/ZionEscape.vcxproj
  ZionEscape/ZionEscape.vcxproj.filters
  ZionEscape/assets/sprites/colliders/D.png
  ZionEscape/assets/sprites/colliders/DL.png
  ZionEscape/assets/sprites/colliders/DR.png
  ZionEscape/assets/sprites/colliders/DRL.png
  ZionEscape/assets/sprites/colliders/G.png
  ZionEscape/assets/sprites/colliders/L.png
  ZionEscape/assets/sprites/colliders/R.png
  ZionEscape/assets/sprites/colliders/RL.png
  ZionEscape/assets/sprites/colliders/T.png
  ZionEscape/assets/sprites/colliders/TD.png
  ZionEscape/assets/sprites/colliders/TDL.png
  ZionEscape/assets/sprites/colliders/TDR.png
  ZionEscape/assets/sprites/colliders/TL.png
  ZionEscape/assets/sprites/colliders/TR.png
  ZionEscape/assets/sprites/colliders/TRL.png
Labels: enhancement

#10 Added optional map generator seed
  ZionEscape/Game.h
  ZionEscape/MainActivity.h
  ZionEscape/Map.h
  ZionEscape/Scene.h
Labels: enhancement

#11 Removed saved instance of BitmapManager in Scene
  ZionEscape/Scene.h
Labels: enhancement

#15 Added the DrawHearts method
  ZionEscape/Game.h
  ZionEscape/MainActivity.h
  ZionEscape/Player.h
  ZionEscape/assets/sprites/misc/heart.png
Labels: enhancement

#21 Added Custom Cursor
  ZionEscape/MainActivity.h
  ZionEscape/assets/sprites/misc/cursor.ico
Labels: enhancement

#16 Fixed the movement bugs
  ZionEscape/Assassin.h
  ZionEscape/Entity.h
  ZionEscape/MainActivity.h
  ZionEscape/MainActivity.resx
  ZionEscape/Sprite.h
Labels: bug

#22 Changed data type of velocity
  ZionEscape/Ally.h
  ZionEscape/Assassin.h
  ZionEscape/Corrupt.h
  ZionEscape/Entity.h
  ZionEscape/NPC.h
  ZionEscape/Player.h
Labels: bug

#18 Added destructors
  ZionEscape/Ally.h
  ZionEscape/Assassin.h
  ZionEscape/BitmapManager.h
  ZionEscape/Corrupt.h
  ZionEscape/Entity.h
  ZionEscape/Game.h
  ZionEscape/Grid.h
  ZionEscape/NPC.h
  ZionEscape/Node.h
  ZionEscape/Pathfinder.h
  ZionEscape/Player.h
  ZionEscape/Sprite.h
Labels: bug

#19 Applied optimizations to map generator
  ZionEscape/DataTypes.h
  ZionEscape/Enums.h
  ZionEscape/Game.h
  ZionEscape/Grid.h
  ZionEscape/MainActivity.h
  ZionEscape/Map.h
  ZionEscape/MathUtils.h
  ZionEscape/Pathfinder.h
  ZionEscape/Scene.h
  ZionEscape/SceneSpawner.h
  ZionEscape/ZionEscape.vcxproj
  ZionEscape/ZionEscape.vcxproj.filters
Labels: enhancement

#27 Fixed scene delete loop
  ZionEscape/Scene.h
Labels: bug

#28 Refactored controller class
  ZionEscape/Ally.h
  ZionEscape/DataTypes.h
  ZionEscape/Game.h
  ZionEscape/MainActivity.h
  ZionEscape/Map.h
  ZionEscape/Node.h
  ZionEscape/Player.h
  ZionEscape/Scene.h
Labels: refactor

#29 Added scene movement and basic collisions
  ZionEscape/Entity.h
  ZionEscape/Enums.h
  ZionEscape/Game.h
  ZionEscape/Grid.h
  ZionEscape/MainActivity.h
  ZionEscape/Map.h
  ZionEscape/Player.h
  ZionEscape/Scene.h
  ZionEscape/Sprite.h
  ZionEscape/assets/sprites/misc/door.png
  ZionEscape/assets/sprites/scenes/scene_1.png
  ZionEscape/assets/sprites/scenes/scene_2.png
  ZionEscape/assets/sprites/scenes/scene_3.png
  ZionEscape/assets/sprites/scenes/scene_4.png
Labels: feature

#30 Created UI controller
  ZionEscape/Enums.h
  ZionEscape/Game.h
  ZionEscape/MainActivity.h
  ZionEscape/Player.h
  ZionEscape/UI.h
  ZionEscape/ZionEscape.vcxproj
  ZionEscape/ZionEscape.vcxproj.filters
  ZionEscape/assets/sprites/misc/credits.png
  ZionEscape/assets/sprites/misc/menu-bg.png
Labels: feature

#24 Added Simple Damage System
  ZionEscape/Assassin.h
  ZionEscape/Game.h
  ZionEscape/MainActivity.h
  ZionEscape/NPC.h
Labels: feature

#31 Fixed pathfinder
  ZionEscape/Ally.h
  ZionEscape/Assassin.h
  ZionEscape/Corrupt.h
  ZionEscape/Entity.h
  ZionEscape/Game.h
  ZionEscape/MainActivity.h
  ZionEscape/MainActivity.resx
  ZionEscape/NPC.h
  ZionEscape/Player.h
Labels: bug

#32 Added NPC generation in each scene
  ZionEscape/Game.h
  ZionEscape/Map.h
  ZionEscape/Scene.h
Labels: feature

#23 Added Shooting Bullets
  ZionEscape/Bullet.h
  ZionEscape/Corrupt.h
  ZionEscape/Game.h
  ZionEscape/MainActivity.h
  ZionEscape/Player.h
  ZionEscape/Scene.h
  ZionEscape/UI.h
  ZionEscape/ZionEscape.vcxproj
  ZionEscape/ZionEscape.vcxproj.filters
  ZionEscape/assets/sprites/misc/bullet.png
Labels: feature

#25 Added Corrupt Convertion
  ZionEscape/Game.h
  ZionEscape/Scene.h
  ZionEscape/Sprite.h
Labels: feature

#33 Added PR
  ZionEscape/Game.h
  ZionEscape/MainActivity.h
  ZionEscape/MainActivity.resx
  ZionEscape/Map.h
  ZionEscape/MessageBox.h
  ZionEscape/ZionEscape.vcxproj
  ZionEscape/ZionEscape.vcxproj.filters
  ZionEscape/assets/sprites/misc/messagebox.png
  ZionEscape/assets/sprites/misc/messagebox_thicc.png
Labels: feature

#34 Stopped the MessageBox
  ZionEscape/Game.h
  ZionEscape/MainActivity.h
Labels: bug
